### ISSUE TITLE
Composer installation issue?

### ISSUE THREAD

**Issue by mattpramschufer** [api-platform/postman-collection-generator#12]
`[InvalidArgumentException]                                                                                                                                                 
  Could not find package api-platform/postman-collection-generator at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
`

I get his when I run
`php composer.phar require --dev api-platform/postman-collection-generator`

**Comment by vincentchalamon** [comment]
Hi @mattpramschufer,

Indeed, it's a bug in the doc. You should better use `php composer.phar require --dev api-platform/postman-collection-generator:dev-master` for the moment, as this bundle is not stable yet. Check [Composer doc](https://getcomposer.org/doc/03-cli.md#require) for more informations.

Can you open a PR on current repo to fix this mistake in the doc please?

**Comment by mattpramschufer** [comment]
Well I did the PR before I actually tested it... 

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for api-platform/postman-collection-generator dev-master -> satisfiable by api-platform/postman-collection-generator[dev-master].
    - api-platform/postman-collection-generator dev-master requires api-platform/core ~1.1@beta -> satisfiable by api-platform/core[v1.1.0, v1.1.1].
    - api-platform/core v1.1.0 requires phpdocumentor/reflection ^1.0.7 -> satisfiable by phpdocumentor/reflection[1.0.7].
    - api-platform/core v1.1.1 requires phpdocumentor/reflection ^1.0.7 -> satisfiable by phpdocumentor/reflection[1.0.7].
    - Conclusion: don't install phpdocumentor/reflection 1.0.7

Installation failed, reverting ./composer.json to its original content.
[`

**Comment by vincentchalamon** [comment]
Your error is up to api-platform dependency on `phpdocumentor/reflection`. You can search for an existing issue/PR on the dedicated repository: https://github.com/api-platform/core
