### ISSUE TITLE
Supports API Platform 2

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/postman-collection-generator#2]
To supports API Platform 2, it should be interesting to add an `Adapter` feature in this bundle, like `APIPlatform1Adapter` & `APIPlatform2Adapter` (and feel free for other supports)

**Comment by vincentchalamon** [comment]
APIPlatform2 supports [Swagger](http://swagger.io/)

**Comment by dunglas** [comment]
I wasn't aware of this feature: https://www.getpostman.com/docs/importing_swagger

Nice! Do you think it worth it to mention that in the readme (for people wanting to use this bundle with API Platform
2)?

**Comment by vincentchalamon** [comment]
At least, mention that current project is dedicated to API Platform 1, and put this feature link in the readme for API Platform 2.
